import { type Product } from "@prisma/client";

export const products: Product[] = [
  {
    "id": "1",
    "productTitle": "Adjustable Office Chair",
    "image": "/products/Chair - Black - Adjustable Office Chair.jpg",
    "price": 159,
    "status": "New",
    "category": "Chair",
    "tag": "Modern",
    "color": "Black",
    "description": "",
    "createdBy": ""
  },
  {
    "id": "2",
    "productTitle": "Rustic Wooden Dining Table",
    "image": "/products/Table - Brown - Rustic Wooden Dining Table (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 849,
    "status": "Popular",
    "category": "Table",
    "tag": "Stylish",
    "color": "Brown"
  },
  {
    "id": "3",
    "productTitle": "Contemporary Floor Lamp",
    "image": "/products/Lamp - Black - Contemporary Floor Lamp (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 1299,
    "status": "Popular",
    "category": "Lamp",
    "tag": "Ambient",
    "color": "Black"
  },
  {
    "id": "4",
    "productTitle": "Compact Nightstand",
    "image": "/products/Drawer - Brown - Compact Nightstand (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 499,
    "status": "Popular",
    "category": "Drawer",
    "tag": "Minimalistic",
    "color": "Brown"
  },
  {
    "id": "5",
    "productTitle": "Queen Size Canopy Bed",
    "image": "/products/Bed - Brown - Queen Size Canopy Bed (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 1499,
    "status": "Popular",
    "category": "Bed",
    "tag": "Luxurious",
    "color": "Brown"
  },
  {
    "id": "6",
    "productTitle": "Classic Bookshelf",
    "image": "/products/Bookshelf - Brown - Contemporary Bookcase (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 479,
    "status": "New",
    "category": "Bookshelf",
    "tag": "Modern",
    "color": "Brown"
  },
  {
    "id": "7",
    "productTitle": "L-shaped Sectional Sofa",
    "image": "/products/Sofa - White - L-shaped Sectional Sofa.jpg",
    "description": "",
    "createdBy": "",
    "price": 799,
    "status": "Popular",
    "category": "Sofa",
    "tag": "Elegant",
    "color": "White"
  },
  {
    "id": "8",
    "productTitle": "Classic Rocking Chair",
    "image": "/products/Chair - Brown - Classic Rocking Chair (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 189,
    "status": "New",
    "category": "Chair",
    "tag": "Stylish",
    "color": "Brown"
  },
  {
    "id": "9",
    "productTitle": "Glass Top Coffee Table",
    "image": "/products/Table - Brown - Glass Top Coffee Table (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 349,
    "status": "Popular",
    "category": "Table",
    "tag": "Minimalistic",
    "color": "Brown"
  },
  {
    "id": "10",
    "productTitle": "Vintage Desk Lamp",
    "image": "/products/Lamp - Black - Vintage Desk Lamp (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 899,
    "status": "New",
    "category": "Lamp",
    "tag": "Ambient",
    "color": "Black"
  },
  {
    "id": "11",
    "productTitle": "Spacious Chest of Drawers",
    "image": "/products/Drawer - Brown - Spacious Chest of Drawers.jpg",
    "description": "",
    "createdBy": "",
    "price": 899,
    "status": "Popular",
    "category": "Drawer",
    "tag": "Modern",
    "color": "Brown"
  },
  {
    "id": "12",
    "productTitle": "Sleek Platform Bed",
    "image": "/products/Bed - Brown - Sleek Platform Bed (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 1299,
    "status": "New",
    "category": "Bed",
    "tag": "Minimalistic",
    "color": "Brown"
  },
  {
    "id": "13",
    "productTitle": "Floating Wall Shelf",
    "image": "/products/Bookshelf - Brown - Floating Wall Shelf (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 89,
    "status": "Popular",
    "category": "Bookshelf",
    "tag": "Stylish",
    "color": "Brown"
  },
  {
    "id": "14",
    "productTitle": "Velvet Upholstered Sofa",
    "image": "/products/Sofa - Brown - Velvet Upholstered Sofa (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 1399,
    "status": "New",
    "category": "Sofa",
    "tag": "Luxurious",
    "color": "Brown"
  },
  {
    "id": "15",
    "productTitle": "Mid-century Armchair",
    "image": "/products/Chair - Brown - Mid-century Armchair (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 799,
    "status": "Popular",
    "category": "Chair",
    "tag": "Modern",
    "color": "Brown"
  },
  {
    "id": "16",
    "productTitle": "Round Glass Dining Table",
    "image": "/products/Table - Black - Round Glass Dining Table (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 599,
    "status": "New",
    "category": "Table",
    "tag": "Elegant",
    "color": "Black"
  },
  {
    "id": "17",
    "productTitle": "Industrial Desk Lamp",
    "image": "/products/Lamp - Black - Industrial Desk Lamp (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 399,
    "status": "Popular",
    "category": "Lamp",
    "tag": "Modern",
    "color": "Black"
  },
  {
    "id": "18",
    "productTitle": "Minimalist Bedside Table",
    "image": "/products/Table - Brown - Minimalist Bedside Table (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 129,
    "status": "New",
    "category": "Drawer",
    "tag": "Minimalistic",
    "color": "Brown"
  },
  {
    "id": "19",
    "productTitle": "Four Poster Canopy Bed",
    "image": "/products/Bed - Brown - Four Poster Canopy Bed (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 999,
    "status": "Popular",
    "category": "Bed",
    "tag": "Luxurious",
    "color": "Brown"
  },
  {
    "id": "20",
    "productTitle": "Contemporary Bookcase",
    "image": "/products/Bookshelf - Brown - Contemporary Bookcase (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 899,
    "status": "New",
    "category": "Bookshelf",
    "tag": "Stylish",
    "color": "Brown"
  },
  {
    "id": "21",
    "productTitle": "Queen Canopy Bed - Additional View with Gold Trim",
    "image": "/products/Bed - Brown - Queen Size Canopy Bed (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 149,
    "category": "Bed",
    "tag": "Luxurious",
    "color": "Brown",
    "status": "Regular"
  },
  {
    "id": "22",
    "productTitle": "Four Poster Canopy Bed - Side View in Oak Finish",
    "image": "/products/Bed - Brown - Four Poster Canopy Bed (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 699,
    "category": "Bed",
    "tag": "Elegant",
    "color": "Brown",
    "status": "Regular"
  },
  {
    "id": "23",
    "productTitle": "Sleek Platform Bed - Alternate View with Storage",
    "image": "/products/Bed - Brown - Sleek Platform Bed (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 799,
    "category": "Bed",
    "tag": "Modern",
    "color": "Brown",
    "status": "Regular"
  },
  {
    "id": "24",
    "productTitle": "Contemporary Bookcase - Second Option in Walnut",
    "image": "/products/Bookshelf - Brown - Contemporary Bookcase (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 1899,
    "category": "Bookshelf",
    "tag": "Minimalistic",
    "color": "Brown",
    "status": "Regular"
  },
  {
    "id": "25",
    "productTitle": "Floating Wall Bookshelf - Variant with Adjustable Shelves",
    "image": "/products/Bookshelf - Brown - Floating Wall Bookshelf (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 349,
    "category": "Bookshelf",
    "tag": "Stylish",
    "color": "Brown",
    "status": "Regular"
  },
  {
    "id": "26",
    "productTitle": "Floating Wall Shelf - Second Version with Matte Finish",
    "image": "/products/Bookshelf - Brown - Floating Wall Shelf (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 79,
    "category": "Bookshelf",
    "tag": "Minimalistic",
    "color": "Brown",
    "status": "Regular"
  },
  {
    "id": "27",
    "productTitle": "Classic Rocking Chair - Additional Angle with Cushioned Seat",
    "image": "/products/Chair - Brown - Classic Rocking Chair (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 499,
    "category": "Chair",
    "tag": "Minimalistic",
    "color": "Brown",
    "status": "Regular"
  },
  {
    "id": "28",
    "productTitle": "Mid-century Armchair - Alternate Design with Leather Upholstery",
    "image": "/products/Chair - Brown - Mid-century Armchair (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 299,
    "category": "Chair",
    "tag": "Modern",
    "color": "Brown",
    "status": "Regular"
  },
  {
    "id": "29",
    "productTitle": "Compact Nightstand - Side View with Drawer Organizer",
    "image": "/products/Drawer - White - Compact Nightstand (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 129,
    "category": "Drawer",
    "tag": "Stylish",
    "color": "White",
    "status": "Regular"
  },
  {
    "id": "30",
    "productTitle": "Contemporary Floor Lamp - Second Variation with Adjustable Height",
    "image": "/products/Lamp - Brown - Contemporary Floor Lamp (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 999,
    "category": "Lamp",
    "tag": "Elegant",
    "color": "Brown",
    "status": "Regular"
  },
  {
    "id": "31",
    "productTitle": "Vintage Desk Lamp - Alternate Design with Brass Finish",
    "image": "/products/Lamp - Black - Vintage Desk Lamp (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 79,
    "category": "Lamp",
    "tag": "Modern",
    "color": "Black",
    "status": "Regular"
  },
  {
    "id": "32",
    "productTitle": "Velvet Upholstered Sofa - Additional View with Throw Pillows",
    "image": "/products/Sofa - Brown - Velvet Upholstered Sofa (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 1499,
    "category": "Sofa",
    "tag": "Luxurious",
    "color": "Brown",
    "status": "Regular"
  },
  {
    "id": "33",
    "productTitle": "Minimalist Bedside Table - Second Option with Built-in USB Charger",
    "image": "/products/Table - White - Minimalist Bedside Table (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 299,
    "category": "Table",
    "tag": "Modern",
    "color": "White",
    "status": "Regular"
  },
  {
    "id": "34",
    "productTitle": "Round Glass Dining Table - Alternate View with Chrome Legs",
    "image": "/products/Table - Black - Round Glass Dining Table (1).jpg",
    "description": "",
    "createdBy": "",
    "price": 799,
    "category": "Table",
    "tag": "Elegant",
    "color": "Black",
    "status": "Regular"
  },
  {
    "id": "35",
    "productTitle": "Rustic Wooden Dining Table - Additional View with Matching Bench",
    "image": "/products/Table - Brown - Rustic Wooden Dining Table (2).jpg",
    "description": "",
    "createdBy": "",
    "price": 399,
    "category": "Table",
    "tag": "Ambient",
    "color": "Brown",
    "status": "Regular"
  }
]